### PR TITLE
feat: support square brackets for colors

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Comment by ahku** [comment]
Will this work for all color values? Hex (inc shorthands), rgb(a), hsl, etc?

**Comment by antfu** [comment]
Currently only hex with # prefix. Might need to discuss other usages with the team first.

**Comment by ahku** [comment]
> Currently only hex with # prefix. Might need to discuss other usages with the team first.

OK. I think I saw a Twind demo where the author modified some hsla values within brackets. 

Another question then: is `bg-image-[url]` supported? Not sure if TW supports it, but the usecase if a div should only have a background image above mobile, ie `sm:bg-image-[url]`. It's definitely a nice to have, cuz you can use the new `<sm` variant to override it `<sm:background-none`, or media queried picture srcset.

**Comment by ahku** [comment]
@antfu 

Still having trouble getting this to work. Not sure if I've updated WindiCSS correctly, but I got the other fixes so not sure why this specifically won't work.

I realize that this feature might not be crucial, at least for my private projects. Just wanted to let you know that TW JIT works with any value such as `sm:bg-[rgba(255,255,0,.75)]`.

For the bracket syntax to align with TW I think the implementation is that any value within brackets should be used and parsed as is, eg:

`bg-[value] => background-color: [value]`
`text-[value] => text-color: [value]`
`grid-[value] => grid: [value]`

Etc. 

There is obviously a lot of manual mapping going on here.

**Pull request merged**
