### PR TITLE
feat: types for attributify mode in jsx

### PR DESCRIPTION
**Pull request by antfu**
## Attributify TypeScript Support 

Create `shims.d.ts` with the following content:

### React

```ts
import { AttributifyAttributes } from 'windicss/types/jsx'

declare module 'react' {
  interface HTMLAttributes<T> extends AttributifyAttributes {}
}
```

### Vue 3

```ts
import { AttributifyAttributes } from 'windicss/types/jsx'

declare module '@vue/runtime-dom' {
  interface HTMLAttributes extends AttributifyAttributes {}
}
```

### Attributify with Prefix

```ts
import { AttributifyNames } from 'windicss/types/jsx'

type Prefix = 'w:' // change it to your prefix

interface HTMLAttributes extends Partial<Record<AttributifyNames<Prefix>, string>> {}
```

### CODE REVIEW

**Comment by dioxine** [comment]
Does anyone know how to correctly `declare module` for `svelte`?  Especially `sveltekit`.

**Comment by Pitasi** [comment]
> Does anyone know how to correctly `declare module` for `svelte`? Especially `sveltekit`.

I used the `global.d.ts` file that is created by svelte kit.

I don't know why, but the only way I found it working is to copy/paste the types definition instead of importing them:

```ts
/// <reference types="@sveltejs/kit" />

declare namespace svelte.JSX {
	export declare type UtilityNames = 'p' | 'm' | 'w' | 'h' | 'z' | 'border' | 'grid' | 'flex' | 'bg' | 'text' | 'font' | 'opacity' | 'animate' | 'transition' | 'transform' | 'align' | 'justify' | 'content' | 'pos' | 'box' | 'overflow' | 'underline' | 'list' | 'gradient' | 'divide' | 'gap' | 'ring' | 'icon' | 'container' | 'space' | 'table' | 'order' | 'place' | 'display' | 'shadow' | 'blend' | 'filter' | 'backdrop' | 'cursor' | 'outline' | 'select';
	export declare type VariantNames = 'hover' | 'active' | 'focus' | 'enabled' | 'dark' | 'light' | 'sm' | 'lg' | 'md' | 'xl' | 'xxl' | 'first' | 'last' | 'child' | 'root' | 'before' | 'after' | 'all';
	export declare type AttributifyNames<Prefix extends string = ''> = `${Prefix}${UtilityNames}` | `${Prefix}${VariantNames}` | `${Prefix}${VariantNames}:${UtilityNames}`;

	// eslint-disable-next-line @typescript-eslint/no-empty-interface
	export interface HTMLProps<T> extends Partial<Record<AttributifyNames | keyof HTMLProps<T>, string>> {
	};
}
```

**Comment by johnfrades** [comment]
> ## Attributify TypeScript Support
> Create `shims.d.ts` with the following content:
> 
> ### React
> ```ts
> import { AttributifyAttributes } from 'windicss/types/jsx'
> 
> declare module 'react' {
>   interface HTMLAttributes<T> extends AttributifyAttributes {}
> }
> ```
> 
> ### Vue 3
> ```ts
> import { AttributifyAttributes } from 'windicss/types/jsx'
> 
> declare module '@vue/runtime-dom' {
>   interface HTMLAttributes extends AttributifyAttributes {}
> }
> ```
> 
> ### Attributify with Prefix
> ```ts
> import { AttributifyNames } from 'windicss/types/jsx'
> 
> type Prefix = 'w:' // change it to your prefix
> 
> interface HTMLAttributes extends Partial<Record<AttributifyNames<Prefix>, string>> {}
> ```

Doesn't work man. Im using react 
image

**Comment by zheeeng** [comment]
The shims of Attributify with Prefix reports

```
All declarations of 'HTMLAttributes' must have identical type parameters.ts(2428)
```

**Comment by zheeeng** [comment]
Attributify with Prefix doesn't work on Vite + TypeScript, console.log reports

```
Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.
```

**Comment by xue-xue** [comment]
@zheeeng  I got same error, didn't find solution yet.

**Comment by 251205668** [comment]
```ts
import type { AriaAttributes, DOMAttributes } from 'react'

declare module 'react' {
  export declare type UtilityNames =
      | 'p'
      | 'm'
      | 'w'
      | 'h'
      | 'z'
      | 'border'
      | 'grid'
      | 'flex'
      | 'bg'
      | 'text'
      | 'font'
      | 'opacity'
      | 'animate'
      | 'transition'
      | 'transform'
      | 'align'
      | 'justify'
      | 'content'
      | 'pos'
      | 'box'
      | 'overflow'
      | 'underline'
      | 'list'
      | 'gradient'
      | 'divide'
      | 'gap'
      | 'ring'
      | 'icon'
      | 'container'
      | 'space'
      | 'table'
      | 'order'
      | 'place'
      | 'display'
      | 'shadow'
      | 'blend'
      | 'filter'
      | 'backdrop'
      | 'cursor'
      | 'outline'
      | 'select'

  export declare type VariantNames =
      | 'hover'
      | 'active'
      | 'focus'
      | 'enabled'
      | 'dark'
      | 'light'
      | 'sm'
      | 'lg'
      | 'md'
      | 'xl'
      | 'xxl'
      | 'first'
      | 'last'
      | 'child'
      | 'root'
      | 'before'
      | 'after'
      | 'all'

  export declare type AttributifyNames<Prefix extends string = ''> =
      | `${Prefix}${UtilityNames}`
      | `${Prefix}${VariantNames}${Capitalize<UtilityNames>}`
      | `${Prefix}${VariantNames}`
      | `${Prefix}${VariantNames}${Capitalize<VariantNames>}`
      | `${Prefix}${Capitalize<UtilityNames>}`
      | `${Prefix}${Capitalize<VariantNames>}${Capitalize<UtilityNames>}`
      | `${Prefix}${Capitalize<VariantNames>}`
      | `${Prefix}${Capitalize<VariantNames>}${Capitalize<VariantNames>}`

  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T>, Partial<Record<AttributifyNames | keyof HTMLAttributes<T>, string>> {}
}

```

**Comment by 954545647** [comment]
> 

The same question, have you solved it?

**Comment by XiNiHa** [comment]
@zheeeng @xue-xue @954545647 use `w-` instead of `w:` (since `:` is used for namespace syntax in JSX)

**Comment by martisj** [comment]
Is anyone else seeing this error message?
`An interface declaring no members is equivalent to its supertype` for the react declaration [here](https://github.com/windicss/windicss/pull/322#issue-912738161)
```ts
import { AttributifyAttributes } from 'windicss/types/jsx'

declare module 'react' {
  interface HTMLAttributes<T> extends AttributifyAttributes {}
}
```

**Pull request merged**
