### PR TITLE
fix: fix colors set by default for yellow, green, and purple

### LINKED ISSUE #790: `bg-green-200` is applying `bg-emerald-200`
I am using Nuxt along WindiCSS. When I apply `bg-green-200` to a element is actually applying `bg-emerald-200`

image
image
`rgb(167,243,208)` corresponds to `#a7f3d0` and that is defined in https://github.com/windicss/windicss/blob/67802fe9af47ebcbebd5c5ee4e5cefc740e39506/src/config/colors.ts#L251-L254

but the correct color is `#bbf7d0`.

I don't know what is going on here. I don't even have a `windi.config.ts`

### PR DESCRIPTION
**Pull request by oekazuma**
fix: #790 , #801

The default colors for green, yellow, and purple were not set correctly and have been fixed.

### CODE REVIEW

**Comment by louiss0** [comment]
The docs have not changed to account for what you did the docs are still the same.

image

for green


image

**Comment by antfu** [comment]
This was aligning Tailwind v2, if we change this it would be a breaking change and needs a major bump

**Comment by louiss0** [comment]
> This was aligning Tailwind v2, if we change this it would be a breaking change and needs a major bump 

I just looked at the tailwind docs and this is what 1 found for yellow, green, and purple 

Yellow
image

Green 
image

Purple

image


I know that you do care about the other people but no developer should have to fill in the gaps for the colors that are missing in tailwind. You are not serving the community well by doing this. You should do this now. Oh and by the way tailwind introduced arbitrary variants. 

image

**Comment by Coachonko** [comment]
I hope this gets merged quick

**Comment by oekazuma** [comment]
WIndi CSS has been deprecated and this PR is closed.

**Pull request closed without merging**
