### PR TITLE
fixes #247

### LINKED ISSUE #247: Wrong color is being generated
Using `bg-purple-100` generates `violet-100` instead of `purple-100`

Expected generated CSS:
```
.bg-purple-100 {
    --tw-bg-opacity: 1;
    background-color: rgba(243,232,255,var(--tw-bg-opacity));
}
```

Actual generated CSS:
```
.bg-purple-100 {
    --tw-bg-opacity: 1;
    background-color: rgba(237, 233, 254, var(--tw-bg-opacity));
}
```

### PR DESCRIPTION
**Pull request by cat-ico**

### CODE REVIEW

**Comment by hannoeru** [comment]
I think is @voorjaar prefer use that color, same as other colors like gray and green.

**Comment by cat-ico** [comment]
> I think is @voorjaar preferred use that color, same as other colors like gray and green.

I didn't know there was a different palette, it kind of makes it harder to switch from tailwind to windi
Also since there is a `violet` color, why have two different color names with the same color?

**Comment by hannoeru** [comment]
Looks like tailwind is using the same color as we used.

https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L27

**Comment by cat-ico** [comment]
Not sure where that specific config is being used, but I've just moved my project from tailwind to windi and noticed that the colors don't match. When I use `purple-100` in tailwind it corresponds to the color listed in [their docs](https://tailwindcss.com/docs/customizing-colors#color-palette-reference) which is `#F3E8FF`. In windi `purple-100` is `#EDE9FE`.

**Pull request closed without merging**
