### PR TITLE
feat: new peer utility

### PR DESCRIPTION
**Pull request by Scrum**
@antfu @harlan-zw @wheatjs @QC-L @hannoeru @Techassi @alexanderniebuhr @voorjaar

### CODE REVIEW

**Comment by Scrum** [comment]
@antfu @harlan-zw @wheatjs @QC-L @hannoeru @Techassi @alexanderniebuhr @voorjaar

**Comment by Scrum** [comment]
@antfu @harlan-zw @wheatjs @QC-L @hannoeru @Techassi @alexanderniebuhr @voorjaar

**Comment by alexanderniebuhr** [comment]
@Scrum stop taking all the people please.

**Comment by Scrum** [comment]
> @Scrum stop taking all the people please.

Why ? You are the maintainer of this project and are able to review while the `antfu` is busy with higher priority tasks?

**Comment by alexanderniebuhr** [comment]
Please understand that we saw your pull request and either of the maintainers will review it if they have time for it, and are maintainers of the core package.
If you just make a comment spam tagging everyone it will not make the review happen faster!

**Comment by schelmo** [comment]
this PR made the `first:` and `last:` variant break
`first:` is now `:first` instead of `:first-child`
@Scrum

**Comment by antfu** [comment]
@schelmo Thanks. Made an issue for tracking https://github.com/windicss/windicss/issues/777

**Pull request merged**
