### PR TITLE
feat: semantic screen utilities range, `<sm` and `@sm`

### PR DESCRIPTION
**Pull request by antfu**
https://github.com/windicss/windicss/discussions/28#discussioncomment-392853

```ts
<sm => smaller than this breakpoint
>sm => greater than this breakpoint
@sm => exactly this breakpoint
```

### CODE REVIEW

**Comment by schelmo** [comment]
`>` and `<` behave then like `+` and `-` ?
shouldn't this be more like this?
```
<sm => @media(max-width: 639.9999px)
>sm => @media(min-width: 640.0001px)
@sm => @media(min-width: 640px) and (max-width: 767.9999px) // makes only sense when using mobile first
```

**Comment by antfu** [comment]
Yeah, I think it's more like a semantic change as `-` `+` could be confusing without reading the docs and `<` `>` could be more intuitive. Can you explain a bit why the `0.0001` delta is needed? Thanks

**Comment by ahku** [comment]
Does this mean that you must write +sm for the min width? We should promote mobile-first, and the max and only breakpoints are overrides. I like @sm for between breakpoint.

**Comment by ahku** [comment]
> `>` and `<` behave then like `+` and `-` ?
> 
> shouldn't this be more like this?
> 
> ```
> 
> <sm => @media(max-width: 639.9999px)
> 
> >sm => @media(min-width: 640.0001px)
> 
> @sm => @media(min-width: 640px) and (max-width: 767.9999px) // makes only sense when using mobile first
> 
> ```

This is correct. Min and max breakpoint can not have the same value or there will be bugs att that exact breakpoint value.

**Comment by schelmo** [comment]
> Can you explain a bit why the `0.0001` delta is needed? Thanks

min-height and max-height is always inclusive.
so `min-height: 640px` is like >= 640px
and `max-height: 640px` is like <= 640px
when using `<sm:` i would expect that the variant is smaller than 640px (and not equal)

**Comment by antfu** [comment]
> Does this mean that you must write +sm for the min width? We should promote mobile-first, and the max and only breakpoints are overrides. I like @sm for between breakpoint.

Nope. The bare `sm` is mobile-first just like Tailwind.

**Comment by antfu** [comment]
Changed the range to this:

```
<sm => @media(max-width: 639.9px)
>sm => @media(min-width: 640.1px)
@sm => @media(min-width: 640px) and (max-width: 767.9px)
```

**Pull request merged**
