### PR TITLE
[scroll-snap plugin] add .no-snap to reset snap effect

### PR DESCRIPTION
**Pull request by kreako**
Tailwindcss-scroll-snap provides a .no-snap class to reset snap effet. Ref [here](https://github.com/innocenzi/tailwindcss-scroll-snap#type).

This is useful to reset the snap effect with responsive/breakpoints. (My use case : snap on mobile, no-snap on desktop).

Thanks for your amazing work!

### CODE REVIEW

**Comment by reslear** [comment]
it is available use `snap-none`
let's stick to the spec https://www.w3.org/TR/css-scroll-snap-1/#snap-strictness

**Comment by kreako** [comment]
Oh right... I read the code too quickly searching .no-snap as in the original plugin... :(

Sorry for the noise.

**Comment by reslear** [comment]
@kreako ok) but adhering to specs like border-none, flex-none, bg-none ...)

**Comment by kreako** [comment]
@reslear Yes, snap-none makes totally sense to me !

**Pull request closed without merging**
