### PR TITLE
refactor(typography): ul, ol ::marker pseudo dublicates

### PR DESCRIPTION
**Pull request by reslear**
Снимок экрана 2021-02-22 в 17 58 59

### CODE REVIEW

**Review by voorjaar — COMMENTED** [review]
Thank you. And one question. Does this problem also exist in the tailwind typography plugin?

**Comment by reslear** [comment]
my investigation show problem in normalize 

```
list-style': 'none'
```

https://github.com/windicss/windicss/blob/6b18ae5b816602196b6e72e5ca28167b11aa30da/src/lib/utilities/preflight.ts#L445-L452

not add styles in vite

**Comment by antfu** [comment]
@reslear Can you show me a rerpo? (or are you using markdowns?)

**Comment by reslear** [comment]
@antfu no md
but this i'm use heavy dynamic generation (v-for, named slot, component :is to set ol or ul tag)
run reproduction https://github.com/whalest/vue-editorjs-html
component :is - https://github.com/whalest/vue-editorjs-html/blob/main/src/components/EditorBlocks/EditorBlocksList.vue

**Comment by antfu** [comment]
@reslear in that way the plugin can't detect them. You can add them to the safelist:

```ts
WindiCSS({
  preflight: {
    safelist: 'ol ul'
  }
})
```

This should work then

**Comment by reslear** [comment]
@antfu thx 💪)I had to remember about the safelist )
@voorjaar maybe revert pull )
@antfu @voorjaar what do you think about add option for change full integrate normalize ?)

**Comment by voorjaar** [comment]
We will have a better solution for purge soon.

**Comment by antfu** [comment]
@reslear You can already

```ts
WindiCSS({
  preflight: {
    enableAll: true
  }
})
```

**Comment by reslear** [comment]
@antfu awensome

**Pull request merged**
