### PR TITLE
Create a documentation site for Windi CSS

### PR DESCRIPTION
**Pull request by ElMassimo**
### Description 📖 

This pull request adds a documentation site for Windi CSS.

The plan for now is to host it in GitHub Pages, though Netlify would be a great choice if we apply for their Open Source plan.

### Future Work 🔮 

I'm going to probably start fledging out different sections based on the content we have on the Wiki.

Let's make sure to chat with each other before starting on a section, to avoid rework 😃 

Also, would be nice to crawl it using Algolia, need to check if there's a plan that would work for the windicss organization.

### Screenshots 📷 

Screen Shot 2021-02-15 at 17 56 54

#### Introduction

Screen Shot 2021-02-15 at 17 47 19

### CODE REVIEW

**Comment by voorjaar** [comment]
Excellent!

**Comment by antfu** [comment]
I can handle the Netlify and apply for the Open Source Plan. @voorjaar is that ok for me to host the site on my account first and then transfer it to the Neflify org (might need a few days for the approval)? If so, I can setup the site now.

**Comment by antfu** [comment]
> Algolia

I can apply for it as well

**Comment by voorjaar** [comment]
That doesn't matter, do it.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/blob/26d763afbdcbf43079642cb0f85939c9c87c7dc7/docs/.vitepress/theme/index.js This page miss a style maybe. @ElMassimo

**Comment by ElMassimo** [comment]
@voorjaar Created a Discord server so that we can communicate more easily, please [join here](https://discord.gg/35kwm3us) 😃

**Comment by antfu** [comment]
Think it's better for docs to be in a separate repo so it won't be messed up with the core's setup. Is that good for you @voorjaar? @ElMassimo and I can handle that. -> https://github.com/windicss/docs

**Pull request merged**
