### PR TITLE
feat: expose utils/algorithm

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Comment by voorjaar** [comment]
Which one do you want to use? For reduce some package size. I didn't expose it. If you need it, just merge it by yourself. I'm going to bed.

**Comment by antfu** [comment]
I am using `cssEscape`, or do you think we can bundle `utils/algorithm` into a submodule?

**Comment by voorjaar** [comment]
You can use `processor.e()`, it will do the same job with `cssEscape`

**Comment by antfu** [comment]
Thanks!

**Pull request closed without merging**
