### PR TITLE
feat: theme types

### PR DESCRIPTION
**Pull request by hannoeru**

### CODE REVIEW

**Comment by antfu** [comment]
This is great, nice work Han!

However, I think maybe we can push the types even better. Now we have this without type errors:
image

If you don't mind, I will make some changes and push to this branch directly

**Comment by hannoeru** [comment]
> If you don't mind, I will make some changes and push to this branch directly
Ok 👍

**Comment by antfu** [comment]
Updated. This PR now also adds dts tests for types (similar to [vue-next](https://github.com/vuejs/vue-next/tree/master/test-dts)). And now the type of `Config` would be sure that only one level of `extend` presents and also prevent mixing custom theme and extending the default theme.

**Review by voorjaar — COMMENTED** [review]
Thank you both, this pr is really awesome.

**Pull request merged**
