### PR TITLE
feat: add plugin scroll-snap

### PR DESCRIPTION
**Pull request by reslear**

### CODE REVIEW

**Review by voorjaar — COMMENTED** [review]
Good job, but if you want to add a plugin, you should also update the rollup config and package.json imports. So you can ensure that your plugin is packaged when it is released. I will help you complete this work.

**Comment by reslear** [comment]
Hi @voorjaar thankyou bro) you created powerfully tooling 💪

**Comment by voorjaar** [comment]
By the way, the [corresponding documents](https://github.com/windicss/docs) should be updated too.

**Comment by reslear** [comment]
yup, working 📚

**Pull request merged**
